### ISSUE TITLE
Support for Local account/Sign in names was missing in  MS graph api.

### ISSUE THREAD

**Issue by Rachana6** [microsoftgraph/30DaysMSGraph-TryItOut#3]
i was unable to create local account via new microsoft graph api, as i am using that for all communications,

But userprincipal name was asking domain name, which will be not used for communication,

When will be support provided for local account and sign in names to create a local account in b2c via ms graph api?

or 
any other way to create local account via ms graph api in asp.net core 2.2

**Comment by Marren85** [comment]
I'm also interested in the answer, I've been waiting for almost 2 years for this functionality to be added and want to move away from Azure AD Graph. You can see from [this](https://blogs.msdn.microsoft.com/aadgraphteam/2016/07/08/microsoft-graph-or-azure-ad-graph/) article in 2016 that it was promised "soon" and 3 years has to be classed as soon, surely!

**Comment by BrianTJackett** [comment]
Sorry for delay in responding, didn't have repo alerts set up previously.
@markdstafford or @dkershaw10 any comment?
